dist: trusty
language: python
python:
  - "3.6"
services:
  - docker

#addons:
#  apt:
#    packages:
#      - libssl1.0.0

before_install:

  - pip install -U pip
  - pip install -e ./packages/diana

  # Bug in gpg key request?
  - pip2 install requests==2.5.3

install:
  - pushd stack
  - ansible-playbook -i ../test/local_inv.yml ../test/dstack_play.yml
  - popd

#before_script:

script:

  - python test/test_distrib.py

#after_script:

