dist: trusty
language: python
python:
  - "3.6"
services:
  - docker

before_install:

  - pip install -U pip
  - pip install -e ./packages

install:
  - pushd stack
  - ansible-playbook -i ../test/local_inv.yml ../test/dstack_play.yml
  - popd

#before_script:

script:

  - python test/test_distrib.py

#after_script:

