dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:

  - pip3 install -U pip
  - pip3 install docker-py
  - pip3 install -e ./packages/diana


install:
  - pushd stack
  - python3 ansible-playbook -i ../test/local_inv.yml ../test/dstack_play.yml
  - popd

#before_script:

script:

  - python3 test/test_distrib.py

#after_script:

