dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:

  - python --version
  - python2 --version
  - python3 --version

  - pip install -U pip
  - pip install docker-py
  - pip install -e ./packages/diana


install:
  - pushd stack
  - ansible-playbook -i ../test/local_inv.yml ../test/dstack_play.yml
  - popd

#before_script:

script:

  - python test/test_distrib.py

#after_script:

