---

- name: Copy service config to host
  template:
    src:   services.yml.j2
    dest:  /tmp/services.yml

- name: Build DIANA docker image
  docker_image:
     path: containers/diana
     name: diana/worker
  delegate: localhost

- name: Start Worker
  docker_container:
    name: diana-worker
    image: diana/worker
    state: started
    # Worker needs access to all central services
    links:
      - "broker-redis"
      - "dicom-orthanc"
      - "index-splunk"
    volume:
    # Mount service info
      - "/tmp/services.yml:/usr/src/app/services.yml"
    # File workers need access to host and shared
      - "/data:/data"
    # Learn workers may need access to gpus
    #  - "/dev:/dev:shared"
