---

- name: git diana-star source
  git:
    repo: https://github.com/derekmerck/diana-star
    dest: /opt/diana-star
  become: yes

- name: Copy service config to host
  template:
    src:   services.ymlj2
    dest:  /opt/diana-star/apps/celery/services.yml
  become: yes

- name: Build diana-worker docker image
  docker_image:
     path: /opt/diana-star/stack/containers/diana-worker
     name: diana-worker
#     force: yes
#     nocache: yes

# Should allow for multiple, give them unique ids
- name: Start Worker
  docker_container:
    name:  diana-worker
    image: diana-worker
    state: started
#    # Worker needs access to all central services
#    links:
#      - "broker-redis"
#      - "dicom-orthanc"
#      - "index-splunk"
    volumes:
    # Mount service info
      - "/opt/diana-star/apps/celery/services.yml:/home/celery/diana-star/apps/celery/services.yml"
    # File workers need access to host and shared
      - "/tmp/data:/home/celery/data"
    # Learn workers may need access to gpus
    #  - "/dev:/dev:shared"
    env:
      TZ: America/New_York
      PYTHONPATH: /home/celery/diana-star