---

- name: Copy service config to host
  template:
    src:   services.yml.j2
    dest:  /tmp/services.yml

- name: git diana-star source
  git:
    repo: https://github.com/derekmerck/diana-star
    dest: /opt/diana-star
  become: yes

- name: Build diana-worker docker image
  docker_image:
     path: /opt/diana-star/stack/containers/diana-worker
     name: diana-worker

# Should allow for multiple, give them unique ids
- name: Start Worker
  docker_container:
    name:  diana-worker
    image: diana-worker
    state: started
    # Worker needs access to all central services
    links:
      - "broker-redis"
      - "dicom-orthanc"
      - "index-splunk"
    volume:
    # Mount service info
      - "/tmp/services.yml:/usr/src/app/services.yml"
    # File workers need access to host and shared
      - "/data:/data"
    # Learn workers may need access to gpus
    #  - "/dev:/dev:shared"
