---
# tasks file for orthanc

- name: Install orthanc
  apt:
    name: orthanc

- name: Add orthanc.json
  template:
    src: orthanc.json.j2
    dest: /etc/orthanc/orthanc.json
  notify: restart_orthanc_service

- meta: flush_handlers

- name: Create orthanc user
  user:
    name: orthanc
#    uid: 1001
    group: root
    state: present

- name: Start orthanc
  service:
    name: orthanc
    enabled: true
