---
- set_fact:
    orthanc_pw: "{{ orthanc_pw }}"

- name: Setup Orthanc container
  docker_container:
    name: dicom-orthanc
    image: jodogne/orthanc
    state: started
    ports:
      - "8042:8042"
      - "4242:4242"